name: Elixir CI

on: push

jobs:
  test-elixir-min-version:
    name: Test Elixir 1.6
    
    runs-on: ubuntu-latest
    
    container:
      image: elixir:1.6-slim
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Tests
      run: mix test
    
  test-elixir-latest:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Formatting
      run: mix format --check-formatted
    - name: Credo
      run: mix credo --strict
    - name: Tests
      run: mix test
